# Generated by Django 3.1.3 on 2020-12-04 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='Titulo de la tarea', max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Descripcion de la tarea', null=True)),
                ('taskStatus', models.CharField(default='nan', help_text='Estado de la tarea', max_length=100)),
                ('isComplete', models.BooleanField(default=False)),
                ('taskExpire', models.DateField(help_text='Fecha de expiracion de la tarea')),
                ('taskCreated', models.DateField(auto_now=True, help_text='Fecha de creacion de la tarea')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
